In [9]:
import numpy as np
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
print("my first array:",arr1)
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print("my first multidimensional array:\n",arr2)
print(arr2.ndim)
print(arr2.shape)
print(len(arr2))
data3=[[1,2,3],[5,6,7],[5,6,7]]
arr3=np.array(data3)
print(arr3)
print(arr3.ndim)


my first array: [6.  7.5 8.  0.  1. ]
my first multidimensional array:
 [[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
2
[[1 2 3]
 [5 6 7]
 [5 6 7]]
2


In [7]:
len(arr1)

5

In [3]:
len(arr2)

2

In [4]:
len(arr3)

3

In [10]:
data=np.array([[0.9526,-0.246,-0.8856],[0.5639,0.2376,0.9104]])
print("2D array:\n",data)
print(data.shape)
print(data.dtype)
print(data.ndim)


2D array:
 [[ 0.9526 -0.246  -0.8856]
 [ 0.5639  0.2376  0.9104]]
(2, 3)
float64
2


In [14]:
np.empty((4,5,6))


array([[[1.72723371e-077, 1.72723371e-077, 6.93593633e-310,
         6.93593634e-310, 6.93593865e-310, 6.93593868e-310],
        [6.93593633e-310, 6.93593740e-310, 6.93593868e-310,
         6.93593740e-310, 6.93593635e-310, 6.93593761e-310],
        [6.93593761e-310, 6.93593761e-310, 6.93593761e-310,
         6.93593845e-310, 6.93593846e-310, 6.93593845e-310],
        [6.93593761e-310, 6.93593761e-310, 6.93593761e-310,
         6.93593846e-310, 6.93593740e-310, 6.93593636e-310],
        [6.93593634e-310, 6.93593740e-310, 6.93593741e-310,
         6.93593740e-310, 6.93593740e-310, 6.93593740e-310]],

       [[6.93593740e-310, 6.93593741e-310, 6.93593740e-310,
         6.93593740e-310, 6.93593740e-310, 6.93593740e-310],
        [6.93593740e-310, 6.93593740e-310, 6.93593740e-310,
         6.93593741e-310, 6.93593741e-310, 6.93593741e-310],
        [6.93593740e-310, 6.93593741e-310, 6.93593741e-310,
         6.93593741e-310, 6.93593740e-310, 6.93593740e-310],
        [6.93593740e-310, 6.93

In [13]:
np.linspace(0,4,10)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [15]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#numpy array attributes

In [19]:
import numpy as np
x3=np.random.randint(10,size=(3,4))#2d array
print(x3)

[[3 4 9 3]
 [5 3 1 0]
 [2 3 7 1]]


In [21]:
x3.size

12

In [22]:
print(x3.itemsize,"bytes")

8 bytes


In [23]:
x3.nbytes

96

In [3]:
#datatypes dtypes
import numpy as np

In [7]:
arr1=np.array([1,2,3],dtype=np.float64)
print(arr1)
arr1.dtype

[1. 2. 3.]


dtype('float64')

In [6]:
arr2=np.array([1.5,2.3,3.2],dtype=np.int32)
arr2.dtype

dtype('int32')

In [8]:
# original and type casted
arr=np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [11]:
arr=arr.astype(np.float64)
arr.dtype

dtype('float64')

In [13]:
#string array into numeric form #only numeric strinds not alpha
a=np.array(['1.23','-9.6','42'],dtype=np.string_)
a.dtype

dtype('S4')

In [16]:
a.astype(np.float64)

array([ 1.23, -9.6 , 42.  ])

In [17]:
a.astype(np.float64).dtype

dtype('float64')

In [19]:
#operations
arr=np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [22]:
#add
arr1=arr+arr
print(arr1)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [23]:
arr2=arr-arr
arr3=arr*arr
arr4=arr/arr
print(arr2)
print(arr3)
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
#scalar add/mul/sub/div
print(arr+1)
print(arr-1)
print(arr*2)
print(arr/2)
print(1/arr)

[[2. 3. 4.]
 [5. 6. 7.]]
[[0. 1. 2.]
 [3. 4. 5.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [27]:
#indexing and slicing
arr=np.array.arange(10)
print(arr)

AttributeError: 'builtin_function_or_method' object has no attribute 'arange'

In [29]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
print(arr[5])

5


In [31]:
print(arr[5:8])

[5 6 7]


In [32]:
arr[5:8]=12
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [39]:

a=np.random.randint(10,size=(3,4))
print(a)

[[8 8 1 6]
 [7 7 8 1]
 [5 9 8 9]]


In [40]:
#slicing
print("slice:",a[(0,0)])

slice: 8


In [41]:
print(a[(0,-1)])

6


In [42]:
print(a[(0,-2)])

1


In [45]:
arr1=np.arange(10)
arr_slice=arr1[5:8]
arr_slice[1]=12345
print(arr1)
type(np.arange(10))

[    0     1     2     3     4     5 12345     7     8     9]


numpy.ndarray

In [46]:
#random number generation
samples=np.random.normal(size=(4,4))
print(samples)

[[-1.27814912  1.43737068 -0.07770457  1.08963016]
 [ 0.09654267  1.41866711  1.16827314  0.94718595]
 [ 1.08548703  2.38222445 -0.40602374  0.26644534]
 [-1.35571372 -0.11410253 -0.84423086  0.70564081]]


In [48]:
#transposing
a

array([[8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

In [49]:
a.T

array([[8, 7, 5],
       [8, 7, 9],
       [1, 8, 8],
       [6, 1, 9]])

In [50]:
np.sqrt(a)

array([[2.82842712, 2.82842712, 1.        , 2.44948974],
       [2.64575131, 2.64575131, 2.82842712, 1.        ],
       [2.23606798, 3.        , 2.82842712, 3.        ]])

In [51]:
np.exp(a)

array([[2.98095799e+03, 2.98095799e+03, 2.71828183e+00, 4.03428793e+02],
       [1.09663316e+03, 1.09663316e+03, 2.98095799e+03, 2.71828183e+00],
       [1.48413159e+02, 8.10308393e+03, 2.98095799e+03, 8.10308393e+03]])

In [55]:
np.maximum(a,np.sqrt(a))

array([[8., 8., 1., 6.],
       [7., 7., 8., 1.],
       [5., 9., 8., 9.]])

In [57]:
#mathematical and statistical methods
arr=np.random.randn(5,4)
print(arr)
print(arr.mean())
print(np.mean(arr))
print(arr.sum())
print(np.sum(arr))

[[-0.74385608 -2.5174371  -1.50709602  1.14907613]
 [-1.19357825  1.14104245  1.50944508  1.06777513]
 [-0.68658948  0.01487332 -0.3756659  -0.03822364]
 [ 0.36797447 -0.0447237  -0.30237513 -2.2244036 ]
 [ 0.72400636  0.35900276  1.07612104  0.19214083]]
-0.1016245669174036
-0.1016245669174036
-2.032491338348072
-2.032491338348072


In [58]:
arr.mean(axis=1)

array([-0.90482827,  0.6311711 , -0.27140142, -0.55088199,  0.58781775])

In [61]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr)
print('cumulative sum row wise:\n',arr.cumsum(0))
print('cumulative sum column wise:\n',arr.cumsum(1))
print('cumulative prod row wise:\n',arr.cumprod(0))
print(arr.cumprod(1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
cumulative sum row wise:
 [[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
cumulative sum column wise:
 [[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]
cumulative prod row wise:
 [[ 0  1  2]
 [ 0  4 10]
 [ 0 28 80]]
[[  0   0   0]
 [  3  12  60]
 [  6  42 336]]


In [62]:
arr=np.random.randn(5,4)
print(arr)
arr.sort(0)#ROWWISE
print(arr)
arr.sort(1)#COLUMNWISE
print(arr)

[[ 0.85292596  0.01835718  0.42830357  0.99627783]
 [-0.49114966  0.71267817  1.11334035 -2.15367459]
 [-0.41611148 -1.07089699  0.22113881 -1.12305712]
 [-1.05075796  1.01207905  1.54371643 -0.40211489]
 [ 0.8647491  -0.22686923  0.81116027  0.28779461]]
[[-1.05075796 -1.07089699  0.22113881 -2.15367459]
 [-0.49114966 -0.22686923  0.42830357 -1.12305712]
 [-0.41611148  0.01835718  0.81116027 -0.40211489]
 [ 0.85292596  0.71267817  1.11334035  0.28779461]
 [ 0.8647491   1.01207905  1.54371643  0.99627783]]
[[-2.15367459 -1.07089699 -1.05075796  0.22113881]
 [-1.12305712 -0.49114966 -0.22686923  0.42830357]
 [-0.41611148 -0.40211489  0.01835718  0.81116027]
 [ 0.28779461  0.71267817  0.85292596  1.11334035]
 [ 0.8647491   0.99627783  1.01207905  1.54371643]]


In [63]:
names=np.array(['bob','joe','will','will','joe','joe'])
np.unique(names)


array(['bob', 'joe', 'will'], dtype='<U4')

In [3]:
#RANDOM NUMBER GENERATION
#random.(rand/randint/randn/binpmial/normal/chi-square/uniform)

In [ ]:
#Universal Function(UFUNCS:)

In [32]:
import numpy as np
np.random.seed(0)
def compute_reciprocals(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]#reciprocals
    return output
values=np.random.randint(1,10,size=5)
print(values)
print(compute_reciprocals(values))
%timeit compute_reciprocals(values)#measure 0f execution time

[6 1 4 4 8]
[0.16666667 1.         0.25       0.25       0.125     ]
25.4 µs ± 1.46 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [35]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [38]:
x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [ ]:
#exploring numpys UFUNCS

In [40]:
#array arithmetic
import numpy as np
x=np.arange(4)
print('x   =',x)
print('x+2 =',x+2)
print('x-2 =',x-2)
print('x*2 =',x*2)
print('x/2 =',x/2)
print('x//2=',x//2)

x   = [0 1 2 3]
x+2 = [2 3 4 5]
x-2 = [-2 -1  0  1]
x*2 = [0 2 4 6]
x/2 = [0.  0.5 1.  1.5]
x//2= [0 0 1 1]


In [43]:
print(x)
print(sum(x,2))
print(np.add(x,2))
print(sum(np.add(x,2)))

[0 1 2 3]
8
[2 3 4 5]
14


In [44]:
x+2

array([2, 3, 4, 5])

In [47]:
x=np.array([-2,-1,0,1,2])
print(abs(x))
print(np.absolute(x))
print(np.abs(x))


[2 1 0 1 2]
[2 1 0 1 2]
[2 1 0 1 2]


In [49]:
#trignometry function
theta=np.linspace(0,np.pi,3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [54]:
#exponents and logarithms
x=[1,2,3] 
print(x) 
print('e^x =',np.exp(x)) 
print('2^x =',np.exp2(x)) 
print('3^x =',np.power(3,x))




[1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [55]:
x=[1,2,3,4]
print('x=',x)
print('In(x)   =',np.log(x))
print('log2(x) =',np.log2(x))
print('log10(x)=',np.log10(x))


x= [1, 2, 3, 4]
In(x)   = [0.         0.69314718 1.09861229 1.38629436]
log2(x) = [0.        1.        1.5849625 2.       ]
log10(x)= [0.         0.30103    0.47712125 0.60205999]


In [59]:
#specifyind output
x=np.arange(5)
y=np.empty(5)
np.multiply(x,10,out=y)
#y=np.multyply(x,10)

y

array([ 0., 10., 20., 30., 40.])

In [2]:
#operations is computed more quickly
import numpy as np
big_array=np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

110 ms ± 1.81 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
614 µs ± 67 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
np.min(big_array),np.max(big_array),np.sum(big_array)

(3.297173203353765e-07, 0.9999998714016899, 499977.16684667446)

In [5]:
#computation on arrays:broadcasting
a=np.array([0,1,2])
b=np.array([5,5,5])
a+b

array([5, 6, 7])

In [6]:
a+5

array([5, 6, 7])

In [8]:
m=np.ones((3,3))
a=np.array([0,1,1])
print('broadcasting:\n',m+a)

broadcasting:
 [[1. 2. 2.]
 [1. 2. 2.]
 [1. 2. 2.]]


In [41]:
a=np.arange(3)
b=np.arange(3).reshape(3,1)
print(a.ndim)
print(b.ndim)

print(a)
print(b)
print(a+b)


1
2
[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [42]:
#there are 3 rules for broadcasting(book/notes in drive)


In [11]:
a=np.ones((2,3))
b=np.arange(3)
print('a shape:',a.shape)
print('b shape:',b.shape)

a shape: (2, 3)
b shape: (3,)


In [43]:
#rule1--one to the left of array with fewer dim
#a.shape->(2,3)
#b.shape->(1,3)

In [13]:
#rule2--ones in empty places
#a.shape->(2,3)
#b.shape->(2,3)

#rule3--disagree in dim error raised ,could not broarcast


In [15]:
print('a:\n',a)
print('b:\n',b)
print('a+b:\n',a+b)

a:
 [[1. 1. 1.]
 [1. 1. 1.]]
b:
 [0 1 2]
a+b:
 [[1. 2. 3.]
 [1. 2. 3.]]


In [16]:
arr=np.random.randn(5,5)
print(arr)
print(arr[-4:-1,-3:-1])

[[-0.29406028  0.80410893 -0.95110331  1.62596066  0.25102997]
 [ 0.96206241 -0.39421325 -0.08358055  1.98276725 -0.01759899]
 [-1.32634628 -0.3480381  -0.56499449 -0.92770993 -1.9337034 ]
 [ 0.61507394 -0.27954263 -1.10468656 -1.19438254 -0.12155939]
 [-0.37505264 -0.16566485  0.29148887  1.12258327  0.51097123]]
[[-0.08358055  1.98276725]
 [-0.56499449 -0.92770993]
 [-1.10468656 -1.19438254]]


# advance array manipulation

In [ ]:
# 1.reshaping

In [19]:
a=np.arange(3)
b=np.arange(3).reshape(3,1)

In [20]:
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [21]:
#multidim shape(3,4)=reshape(4,3)

In [22]:
arr=np.arange(15)
print('1D array:\n',arr)
print('5 rows:\n',arr.reshape((5,-1)))
print('3 rows:\n',arr.reshape((-1,3)))

1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
5 rows:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
3 rows:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [24]:
#ravel()
#flatten()
arr=np.arange(15).reshape((5,3))
print('2D array:\n',arr)
print('ravelling array:\n',arr.ravel())
print('flatten array:\n',arr.flatten())

2D array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
ravelling array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
flatten array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [25]:
#2.concatination -joins arrays in order

In [29]:
#axis=0 rowwise
#axis=1 coloumwise
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print(arr1)
print(arr2)
print(np.concatenate([arr1,arr2],axis=0))#(or)np.vstack((arr1,arr2))      vertical stack
print(np.concatenate([arr1,arr2],axis=1))#(or)np.hstack((arr1,arr2))      horizontal stack

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [30]:
#3.repeating elements:repeat()

In [31]:
arr=np.arange(3)
print(arr.repeat(3))

[0 0 0 1 1 1 2 2 2]


In [45]:
print(arr.repeat([2,3,4]))

[0 0 1 1 1 2 2 2 2]


In [46]:
a=arr.repeat([2,3,4])
print(a)

[0 0 1 1 1 2 2 2 2]


In [47]:
[a[3],a[4],a[6]]#fancy indexing

[1, 1, 2]

In [48]:
ind=[3,4,6]
a[ind]

array([1, 1, 2])

In [ ]:
#fast sorting:np.sort   np.argsort

In [49]:
x=np.array([2,1,4,9,5])
print(x)
np.sort(x)

[2 1 4 9 5]


array([1, 2, 4, 5, 9])

In [50]:
#np.argsort returns indices of sorted elements

In [51]:
i=np.argsort(x)
print(i)

[1 0 2 4 3]


In [57]:
#np.sort(y,axis=1)    rowwise for 2D
#np.sort(y,axis=0)    coloumwise for 2D

In [58]:
#numpys structured arrays(heterogenous data)


In [59]:
import numpy as np

name=['alice','bob','cathy','doug']
age=[25,45,37,19]
weight=[55.0,88.4,43.2,35.5]

In [61]:
#creating simple array
x=np.zeros(4,dtype=int)
#creating compound array
data=np.zeros(4,dtype={'names':('name','age','weight'),
                      'formats':('U10','i4','f8')})
#'U10'- translates to 'unicode string of maxlen 10','i4'- translates to '4byte'(i.e.,32bit)integer,
#'f8'- translates to '8byte'(i.e.,64bit)float
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [63]:
data['name']=name
data['age']=age
data['weight']=weight
print(data)
print(type(data))

[('alice', 25, 55. ) ('bob', 45, 88.4) ('cathy', 37, 43.2)
 ('doug', 19, 35.5)]
<class 'numpy.ndarray'>


In [64]:
#get first row of data
data[0]

('alice', 25, 55.)

In [65]:
#get the name from the last row of data
data[-1]['name']

'doug'

In [66]:
#names of age under 30
data[data['age']<30]

array([('alice', 25, 55. ), ('doug', 19, 35.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [68]:
data[data['age']<30]['name']

array(['alice', 'doug'], dtype='<U10')

pandas provide a dataframe object,which is a structure built on mumpyarrays that offers a variety of dada manipulation  functionality